# Generated by Django 5.1.5 on 2025-01-19 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactForms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=50)),
                ('profile', models.CharField(max_length=50)),
                ('message', models.TextField(default='', max_length=1000)),
            ],
        ),
    ]
