# Generated by Django 5.1.5 on 2025-01-19 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0002_rename_contactforms_contactform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactform',
            name='profile',
            field=models.CharField(choices=[('Profile', 'Profile'), ('Dashboard', 'Dashboard'), ('Services', 'Menu (Quotation, Installtion, Service, Other)'), ('Products', 'Product List'), ('Invoice', 'Invoice History'), ('Other', 'Other than Above')], max_length=50),
        ),
    ]
