# Generated by Django 5.1.5 on 2025-01-21 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0003_alter_contactform_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactform',
            name='file',
            field=models.FileField(default='', upload_to='uploads/front/'),
        ),
    ]
