# Generated by Django 5.1.5 on 2025-01-21 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0004_contactform_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactform',
            name='file',
        ),
    ]
