# Generated by Django 5.1.5 on 2025-01-21 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0005_remove_contactform_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactform',
            name='file',
            field=models.FileField(default='', upload_to='uploads/front/'),
        ),
    ]
