# Generated by Django 5.1.5 on 2025-01-21 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0006_contactform_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactform',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/front/'),
        ),
    ]
